# Generated by Django 3.2.16 on 2023-01-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maize', models.FloatField()),
                ('jowar', models.FloatField()),
                ('Brice', models.FloatField()),
                ('DORB', models.FloatField()),
                ('SFPellet', models.FloatField()),
                ('DOGN', models.FloatField()),
                ('soya', models.FloatField()),
                ('RSM', models.FloatField()),
                ('DDGS', models.FloatField()),
                ('GOC', models.FloatField()),
                ('CalcitePowder', models.FloatField()),
                ('stoneGrid', models.FloatField()),
                ('DCP', models.FloatField()),
                ('methionine', models.FloatField()),
                ('lysine', models.FloatField()),
                ('aGeeMicForte', models.FloatField()),
                ('spectraDFM', models.FloatField()),
                ('synerzymeXL', models.FloatField()),
                ('choline', models.FloatField()),
                ('sodiumBicarbonate', models.FloatField()),
                ('salt', models.FloatField()),
                ('ultralyteC', models.FloatField()),
                ('sfCake', models.FloatField()),
            ],
        ),
    ]
