# Generated by Django 3.2.16 on 2023-01-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5)),
                ('maize', models.FloatField()),
                ('jowar', models.FloatField()),
                ('Brice', models.FloatField()),
                ('DORB', models.FloatField()),
                ('SFPellet', models.FloatField()),
                ('DOGN', models.FloatField()),
                ('soya', models.FloatField()),
                ('RSM', models.FloatField()),
                ('DDGS', models.FloatField()),
                ('GOC', models.FloatField()),
                ('CalcitePowder', models.FloatField()),
                ('stoneGrid', models.FloatField()),
                ('DCP', models.FloatField()),
                ('methionine', models.FloatField()),
                ('lysine', models.FloatField()),
                ('aGeeMicForte', models.FloatField()),
                ('spectraDFM', models.FloatField()),
                ('synerzymeXL', models.FloatField()),
                ('choline', models.FloatField()),
                ('sodiumBicarbonate', models.FloatField()),
                ('salt', models.FloatField()),
                ('ultralyteC', models.FloatField()),
                ('sfCake', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('qty', models.IntegerField()),
                ('feed_type', models.CharField(max_length=30)),
                ('maize', models.FloatField()),
                ('jowar', models.FloatField()),
                ('Brice', models.FloatField()),
                ('DORB', models.FloatField()),
                ('SFPellet', models.FloatField()),
                ('DOGN', models.FloatField()),
                ('soya', models.FloatField()),
                ('RSM', models.FloatField()),
                ('DDGS', models.FloatField()),
                ('GOC', models.FloatField()),
                ('CalcitePowder', models.FloatField()),
                ('stoneGrid', models.FloatField()),
                ('DCP', models.FloatField()),
                ('methionine', models.FloatField()),
                ('lysine', models.FloatField()),
                ('aGeeMicForte', models.FloatField()),
                ('spectraDFM', models.FloatField()),
                ('synerzymeXL', models.FloatField()),
                ('choline', models.FloatField()),
                ('sodiumBicarbonate', models.FloatField()),
                ('salt', models.FloatField()),
                ('ultralyteC', models.FloatField()),
                ('sfCake', models.FloatField()),
            ],
        ),
    ]
