# Generated by Django 3.2.16 on 2023-01-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_app', '0002_formula_stockrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
