from django.db import models

# Create your models here.

class Stock(models.Model):
    maize = models.FloatField()
    jowar = models.FloatField()
    Brice = models.FloatField()
    DORB  = models.FloatField()
    SFPellet  = models.FloatField()
    DOGN = models.FloatField()
    soya = models.FloatField()
    RSM = models.FloatField()
    DDGS = models.FloatField()
    GOC = models.FloatField()
    CalcitePowder = models.FloatField()
    stoneGrid = models.FloatField()
    DCP = models.FloatField()
    methionine = models.FloatField()
    lysine = models.FloatField()
    aGeeMicForte = models.FloatField()
    spectraDFM = models.FloatField()
    synerzymeXL = models.FloatField()
    choline = models.FloatField()
    sodiumBicarbonate = models.FloatField()
    salt = models.FloatField()
    ultralyteC = models.FloatField()
    sfCake = models.FloatField()


class StockRecord(models.Model):
    date_time = models.DateTimeField()
    qty = models.IntegerField()
    feed_type = models.CharField(max_length=30)
    maize = models.FloatField()
    jowar = models.FloatField()
    Brice = models.FloatField()
    DORB  = models.FloatField()
    SFPellet  = models.FloatField()
    DOGN = models.FloatField()
    soya = models.FloatField()
    RSM = models.FloatField()
    DDGS = models.FloatField()
    GOC = models.FloatField()
    CalcitePowder = models.FloatField()
    stoneGrid = models.FloatField()
    DCP = models.FloatField()
    methionine = models.FloatField()
    lysine = models.FloatField()
    aGeeMicForte = models.FloatField()
    spectraDFM = models.FloatField()
    synerzymeXL = models.FloatField()
    choline = models.FloatField()
    sodiumBicarbonate = models.FloatField()
    salt = models.FloatField()
    ultralyteC = models.FloatField()
    sfCake = models.FloatField()


class Formula(models.Model):
    type = models.CharField(max_length=5)
    maize = models.FloatField()
    jowar = models.FloatField()
    Brice = models.FloatField()
    DORB  = models.FloatField()
    SFPellet  = models.FloatField()
    DOGN = models.FloatField()
    soya = models.FloatField()
    RSM = models.FloatField()
    DDGS = models.FloatField()
    GOC = models.FloatField()
    CalcitePowder = models.FloatField()
    stoneGrid = models.FloatField()
    DCP = models.FloatField()
    methionine = models.FloatField()
    lysine = models.FloatField()
    aGeeMicForte = models.FloatField()
    spectraDFM = models.FloatField()
    synerzymeXL = models.FloatField()
    choline = models.FloatField()
    sodiumBicarbonate = models.FloatField()
    salt = models.FloatField()
    ultralyteC = models.FloatField()
    sfCake = models.FloatField()